"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Camera, Cpu, Fingerprint, HardHat, Network, Radio, Workflow } from "lucide-react";

const focusAreas = [
  { icon: Network, code: "FIELD / 01", title: "Operasi terhubung", lead: "Teknologi bertemu kebutuhan lapangan.", copy: "Eksplorasi integrasi data operasional, pemantauan peralatan, dan dukungan teknis untuk meningkatkan visibilitas aktivitas industri.", tags: ["Peralatan", "Telematika", "Data operasi"], color: "text-cyan-300", glow: "from-cyan-500/[0.14]" },
  { icon: Workflow, code: "SYSTEMS / 02", title: "Alur kerja digital", lead: "Proses yang lebih jelas dan terukur.", copy: "Solusi perangkat lunak dan infrastruktur teknologi dapat membantu organisasi menyederhanakan proses dan menghubungkan tim.", tags: ["Perangkat lunak", "Cloud", "Otomasi"], color: "text-blue-300", glow: "from-blue-500/[0.14]" },
  { icon: Camera, code: "STUDIO / 03", title: "Konten visual bermakna", lead: "Cerita bisnis menjadi pengalaman visual.", copy: "Videografi, fotografi, editing, dan pascaproduksi membantu menerjemahkan ide menjadi konten visual yang kuat dan relevan.", tags: ["Videografi", "Fotografi", "Editing"], color: "text-violet-300", glow: "from-violet-500/[0.14]" },
];

const principles = [
  { icon: HardHat, title: "Mulai dari lapangan", copy: "Pahami pekerjaan dan tantangan pengguna sebelum menentukan teknologi." },
  { icon: Cpu, title: "Gunakan teknologi yang tepat", copy: "Pilih sistem yang menyelesaikan kebutuhan dengan jelas dan bertanggung jawab." },
  { icon: Fingerprint, title: "Rancang agar terhubung", copy: "Pertimbangkan dampak dan integrasi di seluruh ekosistem sejak awal." },
];

export default function InnovationPage() {
  return (
    <main className="min-h-screen overflow-hidden pb-24 pt-28 md:pt-36">
      <section className="relative px-5 text-center sm:px-8"><div className="absolute left-1/2 top-0 -z-10 h-72 w-[min(90vw,700px)] -translate-x-1/2 rounded-full bg-blue-500/[0.08] blur-[110px]" />
        <motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }} className="mx-auto max-w-4xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-3 py-2 text-[10px] font-semibold uppercase tracking-[.18em] text-slate-300"><Radio size={14} className="text-cyan-300" /> Inovasi lintas pilar</span><h1 className="mt-7 font-display text-4xl font-semibold leading-[1.06] tracking-[-.05em] text-white sm:text-6xl md:text-7xl">Solusi dimulai saat<br className="hidden sm:block" /> <span className="bg-gradient-to-r from-cyan-200 via-blue-300 to-slate-400 bg-clip-text text-transparent">berbagai bidang terhubung.</span></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg sm:leading-8">Kami melihat inovasi sebagai cara menyatukan kebutuhan industri, sistem digital, dan komunikasi visual menjadi solusi yang lebih utuh.</p></motion.div>
      </section>

      <section className="mx-auto mt-20 max-w-7xl px-5 sm:px-8 lg:mt-28 lg:px-12"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-500">Ruang eksplorasi</p><h2 className="mt-3 font-display text-3xl font-semibold text-white sm:text-4xl">Peluang inovasi ekosistem.</h2></div><p className="max-w-md text-sm leading-6 text-slate-400">Area berikut menggambarkan arah kolaborasi yang dapat dikembangkan sesuai kebutuhan mitra.</p></div><div className="grid gap-4 lg:grid-cols-3">{focusAreas.map(({ icon: Icon, code, title, lead, copy, tags, color, glow }, i) => <motion.article key={code} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-50px" }} transition={{ delay: i * .12 }} className="group relative overflow-hidden rounded-3xl border border-white/[0.08] bg-[#101620] p-6 transition duration-300 hover:-translate-y-1 hover:border-white/20 sm:p-7"><div className={`pointer-events-none absolute -right-16 -top-20 h-56 w-56 rounded-full bg-gradient-to-br ${glow} to-transparent blur-3xl transition group-hover:scale-125`} /><div className="relative flex items-center justify-between"><Icon size={22} className={color} /><span className="text-[10px] tracking-[.16em] text-slate-600">{code}</span></div><h3 className="relative mt-8 font-display text-xl font-semibold text-white">{title}</h3><p className="relative mt-2 text-sm font-medium text-slate-300">{lead}</p><p className="relative mt-3 min-h-[96px] text-sm leading-6 text-slate-400">{copy}</p><div className="relative mt-5 flex flex-wrap gap-2">{tags.map((tag) => <span key={tag} className="rounded-full border border-white/[0.08] bg-white/[0.025] px-2.5 py-1 text-[10px] text-slate-400">{tag}</span>)}</div></motion.article>)}</div></section>

      <section className="mt-24 border-y border-white/[0.07] bg-white/[0.015] px-5 py-20 sm:px-8 lg:mt-32 lg:px-12"><div className="mx-auto max-w-7xl"><motion.div initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-9 max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-500">Prinsip pengembangan</p><h2 className="mt-3 font-display text-3xl font-semibold text-white sm:text-4xl">Teknologi harus memberi dampak.</h2><p className="mt-4 text-sm leading-6 text-slate-400">Pendekatan yang berangkat dari kebutuhan dan kolaborasi lintas disiplin membantu menjaga inovasi tetap relevan.</p></motion.div><div className="grid gap-3 md:grid-cols-3">{principles.map(({ icon: Icon, title, copy }, i) => <motion.div key={title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .1 }} className="flex gap-4 rounded-2xl border border-white/[0.08] bg-[#101620] p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/[0.08] bg-white/[0.04] text-cyan-200"><Icon size={18} /></span><div><h3 className="text-sm font-semibold text-white">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{copy}</p></div></motion.div>)}</div></div></section>

      <section className="mx-auto mt-20 max-w-7xl px-5 sm:px-8 lg:mt-28 lg:px-12"><div className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-[#151e2a] to-[#0d121a] p-7 sm:p-10 md:flex md:items-center md:justify-between"><div className="absolute -right-10 -top-28 h-72 w-72 rounded-full bg-cyan-300/[0.07] blur-[90px]" /><div className="relative"><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-200">Kolaborasi</p><h2 className="mt-3 font-display text-2xl font-semibold text-white sm:text-3xl">Punya tantangan yang ingin dipecahkan?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Mari mulai dengan memahami kebutuhan Anda dan menemukan kapabilitas grup yang paling sesuai.</p></div><Link href="/contact" className="relative mt-7 inline-flex w-fit items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#0a0d14] transition hover:bg-cyan-100 md:mt-0">Mulai berdiskusi <ArrowRight size={16} /></Link></div></section>
    </main>
  );
}
